создание класса с бд. DataBaseWorker
it-top-shambala/MyReceipts pull request #10
Opened 2024-07-02 15:53 UTC by signore89

2024-07-02 16:10 UTC, bashkircoder commented on MyReceipts.App/DataBaseWorker.cs
1. убрать метод Equel
2. убрать методы по поиску рецептов по ингредиентам
3. сохранение в БД сделать двумя методами с одинаковым названием "SaveFavoriteRecipeToDB" (с разными данными на вход)
4. добавить проверку исключений

2024-07-02 16:12 UTC, bashkircoder reviewed
исправить

2024-07-02 16:35 UTC, anst-foto requested changes
Переделать

2024-07-02 16:35 UTC, anst-foto commented on MyReceipts.App/DataBaseWorker.cs
> +    internal static class DataBaseWorker
❓ `static`

2024-07-02 16:35 UTC, anst-foto commented on MyReceipts.App/DataBaseWorker.cs
> +        public static ICollection<Recipe> GetRecipes()
```suggestion
        public static IEnumerable<Recipe> GetRecipes()
```

2024-07-02 16:35 UTC, anst-foto commented on MyReceipts.App/DataBaseWorker.cs
> +        }
```suggestion
        public static void SaveFavoriteRecipes(Recipe recipes)
        {
            using (DBContext dbContext = new DBContext())
            {
                dbContext.Recipes.Add(recipes);
                dbContext.SaveChanges();
            }
        }
        public static void SaveFavoriteRecipes(List<Recipe> recipes)
        {
            using (DBContext dbContext = new DBContext())
            {
                dbContext.Recipes.AddRange(recipes);
                dbContext.SaveChanges();
            }
        }
```

2024-07-02 16:35 UTC, anst-foto commented on MyReceipts.App/DataBaseWorker.cs
> +                    for (global::System.Int32 i = 0; i < LenghtKey; i++)
```suggestion
                    for (int i = 0; i < LenghtKey; i++)
```

2024-07-02 16:35 UTC, anst-foto commented on MyReceipts.App/DataBaseWorker.cs
> +                    var ingredientsForRecipe = item.Ingredients.ToList();
❓ зачем `List<Ingredients>?` приводить к `List<Ingredients>`

2024-07-04 17:56 UTC, bashkircoder reviewed
надо поправить

2024-07-04 17:56 UTC, bashkircoder commented on MyReceipts.App/DataBaseWorker.cs
Объединить классы. На вход в DataBaseWorker будет приходить список расширенных рецептов, его надо будет подогнать под классы для БД, только после этого будет проходить реализация метода по записи рецептов в БД

2024-07-06 16:46 UTC, merged