Feature/database
it-top-shambala/MyReceipts pull request #6
Opened 2024-06-25 17:47 UTC by bashkircoder

Review code to merge.

2024-06-25 17:55 UTC, Chugerbuller requested changes
Внести обговоренные изменения

2024-06-25 17:55 UTC, Chugerbuller commented on MyReceipts.App/Ingredient.cs
добавить название единиц измерения

2024-06-26 16:15 UTC, anst-foto requested changes
Переделать

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/DBContext.cs
> +        Database.EnsureCreated();
```suggestion
```

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/Ingredient.cs
> +            ? throw new ArgumentNullException()
```suggestion
            ? throw new ArgumentNullException(nameof(Name)) 
```

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/Ingredient.cs
> +    }
Либо используете автосвойство, либо добавляете приватную переменную

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/MyReceipts.App.csproj
> +    </ItemGroup>
```suggestion
    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
    </ItemGroup>
```

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/MyReceipts.App.zip
Сей файл не должен тут быть

2024-06-26 16:15 UTC, anst-foto commented on MyReceipts.App/Recipe.cs
> +    public Ingredient Ingredient { get; set; }
```suggestion
    public List<Ingredient> Ingredients { get; set; }
```

2024-06-27 15:44 UTC, anst-foto approved these changes
🆗

2024-06-27 15:49 UTC, merged